api_platform:
  title: 'Taskly'
  version: 1.0.0
  swagger:
    api_keys:
      Bearer:
        name: Authorization
        type: header

  formats:
    jsonld: ['application/ld+json']
    jsonld_collection: ['application/ld+json']

  defaults:
    stateless: true
    cache_headers:
      vary: ["Content-Type", "Authorization", "Origin"]

  collection:
    pagination:
      page_parameter_name: page
