gesdinet_jwt_refresh_token:
  refresh_token_class: App\Entity\RefreshToken
  firewall: 'api'
  return_expiration: true
  token_parameter_name: 'refresh'
  single_use: true
  user_provider: security.user.provider.concrete.app_user_provider
  return_expiration_parameter_name: 'refresh_expiration'
  ttl: 604800
  cookie:
    enabled: true
    same_site: 'lax'
    secure: false
    path: '/'
    domain: 'localhost'
    http_only: true
    partitioned: true
    remove_token_from_body: false