gesdinet_jwt_refresh_token:
  refresh_token_class: App\Entity\RefreshToken
  return_expiration: true
  token_parameter_name: 'refresh_token'
  firewall: 'api'
  single_use: true
  return_expiration_parameter_name: 'refresh_expiration'
  ttl: 604800
  cookie:
    enabled: true
    remove_token_from_body: false
