vich_uploader:
  db_driver: orm
  metadata:
    type: attribute
  mappings:
    media_object:
      uri_prefix: /media
      upload_destination: '%kernel.project_dir%/public/media'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    user_avatar:
      uri_prefix: /uploads/avatars
      upload_destination: '%kernel.project_dir%/public/uploads/avatars'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      delete_on_remove: true
      delete_on_update: true
      inject_on_load: true
